# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b7a644f5c624b1c5fa1149a08b3a16f34c0bc6b6ab261d5d44badb292f6c6be9954339b543bded3ed04eb707d1b49049c277c4f4938ba7560670a9c9a009d92a

test:
  secret_key_base: 34bee3ea265ac864c2fbe3e87a1b1bf0a7fdbf62c264ec5ad74332e102d9032cfe42f6e07ea0b025db6edcfea8eb158a23446e651a314c1c71f031c483ab88b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
